name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.14
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  flutter_staggered_grid_view: ^0.3.1
  provider: ^6.0.2
  path_provider: ^2.0.9
  image: ^3.1.3
  intl:
  firebase_core: ^1.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
